default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: postgres
  password: 1234

development:
  <<: *default
  database: online_school_development

test:
  <<: *default
  database: online_school_test

production:
  <<: *default
  database: online_school_production
  username: online_school
  password: <%= ENV['ONLINE_SCHOOL_DATABASE_PASSWORD'] %>
